### ISSUE TITLE
CPMA support

### ISSUE THREAD

**Issue by luismbo** [treyyoder/quakejs-docker#3]
Adding in CPMA (https://playmorepromode.com) and its fun variations like instagib, Clan Arena, CTF, etc would be awesome.

**Comment by ratnose** [comment]
The server config is in the container... no idea other than that. :D

**Comment by treyyoder** [comment]
@ratnose is correct, the server config is in the container.  But you can edit it:

exec into the container:
 ```docker exec -it quakejs bash``` and then navigate to:

/quakejs/base/baseq3
/quakejs/base/cpma

From there you can `vi server.cfg` to edit it.

You could also copy a config file from your host machine to your container:
`docker cp server.cfg quakejs:/quakejs/base/baseq3/server.cfg`

With both of these methods restart the container afterwards:
`docker restart quakejs`

**Comment by luismbo** [comment]
Isn't entrypoint.sh hardcoded to `baseq3`?:

  ```node build/ioq3ded.js +set fs_game baseq3 set dedicated 1 +exec server.cfg```

(It's curious that the server side runs a Javascript version of the server rather than the plain C++ version. :-))

Have you considered moving the configuration and content to a volume. IIUC, it's bad practice to modify containers. BTW, on the server side, where is the content (such as pak0.pak and various maps, etc) pulled from and when?

**Comment by treyyoder** [comment]
Yeah, you'd have to update entrypoint.sh changing it to `cpma` instead of `baseq3` in the container as well.

Right, you shouldn't be changing a container, but this project isn't official, so do so at your own risk.  I was just offering a work around until what you are asking for is implemented.

It's running in JavaScript because that is what quakeJS is.

I did think about putting the config/maps on a volume, I'll try to prototype that out and see if it adds complexity.  I want to keep this as simple as possible for people to be able to pull and run with little to no configuration required.

**Comment by luismbo** [comment]
@treyyoder the key Javascript part is certainly the client since that lets us run Quake on a browser. There's no benefit in running the server via Javascript, is there?

**Comment by treyyoder** [comment]
@luismbo Read this section on the main quakejs repo from which this is derived, and the part about quakejs using websockets and how native builds and web builds currently can't interact with eachother.
https://github.com/inolen/quakejs#running-a-dedicated-server

**Comment by luismbo** [comment]
Oh, interesting. Thanks for the pointer @treyyoder.
